'use client'
import { useEffect, useState } from 'react'
import { screeningAPI, jobsAPI } from '@/lib/api'
import { Star, Trophy, X, ChevronRight } from 'lucide-react'

export default function HRShortlistPage() {
  const [screenings, setScreenings] = useState<any[]>([])
  const [jobs, setJobs]             = useState<any[]>([])
  const [selectedJob, setSelectedJob] = useState('')
  const [result, setResult]         = useState<any>(null)
  const [selected, setSelected]     = useState<any>(null)
  const [loading, setLoading]       = useState(false)

  useEffect(() => {
    jobsAPI.list().then(r => setJobs(r.data.data)).catch(() => {})
    screeningAPI.list({ status: 'completed' }).then(r => setScreenings(r.data.data)).catch(() => {})
  }, [])

  useEffect(() => {
    if (!selectedJob) return
    setLoading(true)
    screeningAPI.latest(selectedJob)
      .then(r => setResult(r.data.data))
      .catch(() => setResult(null))
      .finally(() => setLoading(false))
  }, [selectedJob])

  const rankStyle = (rank: number) => {
    if (rank === 1) return 'bg-amber-100 border-amber-300 text-amber-700'
    if (rank === 2) return 'bg-slate-100 border-slate-300 text-slate-600'
    if (rank === 3) return 'bg-orange-100 border-orange-300 text-orange-600'
    return 'bg-sky-50 border-sky-200 text-sky-600'
  }

  const shortlist = result?.shortlist || []

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="font-display text-2xl font-bold text-sky-950">AI Shortlists</h1>
          <p className="text-sky-400 text-sm mt-1">View Gemini-generated candidate rankings</p>
        </div>
        <select value={selectedJob} onChange={e => setSelectedJob(e.target.value)}
          className="bg-white border border-sky-200 rounded-xl px-4 h-10 text-sm text-sky-700 outline-none min-w-[260px]">
          <option value="">Select a job to view shortlist…</option>
          {jobs.map(j => <option key={j._id} value={j._id}>{j.title}</option>)}
        </select>
      </div>

      {!selectedJob && (
        <div className="bg-white rounded-2xl p-16 text-center shadow-card border border-sky-50">
          <Star className="w-12 h-12 text-sky-200 mx-auto mb-4" />
          <h3 className="font-display text-xl font-bold text-sky-900 mb-2">No shortlist selected</h3>
          <p className="text-sky-400">Select a job above to view its AI-generated shortlist.</p>
        </div>
      )}

      {selectedJob && loading && (
        <div className="grid md:grid-cols-2 gap-4">
          {[...Array(4)].map((_,i) => <div key={i} className="bg-white rounded-2xl h-56 shimmer" />)}
        </div>
      )}

      {selectedJob && !loading && !result && (
        <div className="bg-white rounded-2xl p-16 text-center shadow-card border border-sky-50">
          <Trophy className="w-12 h-12 text-sky-200 mx-auto mb-4" />
          <h3 className="font-display text-xl font-bold text-sky-900 mb-2">No screening run yet</h3>
          <p className="text-sky-400 mb-6">Run AI Screening for this job to generate a shortlist.</p>
        </div>
      )}

      {result && shortlist.length > 0 && (
        <>
          {/* Hero stats */}
          <div className="bg-sky-950 rounded-2xl p-6 text-white flex items-center gap-6 flex-wrap">
            <div className="flex items-center gap-4">
              <Trophy className="w-10 h-10 text-sky-400 flex-shrink-0" />
              <div>
                <h2 className="font-display text-xl font-bold">{result.jobTitle}</h2>
                <p className="text-sky-400 text-sm">Generated by Gemini AI</p>
              </div>
            </div>
            <div className="ml-auto flex gap-8">
              {[
                { label: 'Screened',    value: result.totalApplicantsEvaluated },
                { label: 'Shortlisted', value: shortlist.length },
                { label: 'Top Score',   value: Math.max(...shortlist.map((c: any) => c.matchScore)) },
              ].map(s => (
                <div key={s.label} className="text-center">
                  <div className="font-display text-3xl font-bold text-sky-300">{s.value}</div>
                  <div className="text-sky-500 text-xs uppercase tracking-wide">{s.label}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Candidate cards */}
          <div className="grid md:grid-cols-2 gap-4">
            {shortlist.map((c: any) => (
              <div key={c.applicantId}
                onClick={() => setSelected(c)}
                className={`bg-white rounded-2xl p-6 shadow-card card-hover border cursor-pointer relative overflow-hidden
                  ${c.rank <= 3 ? 'border-sky-200' : 'border-sky-50'}`}>
                {c.rank <= 3 && <div className="absolute top-0 left-0 right-0 h-0.5 bg-sky-gradient" />}

                {/* Rank badge */}
                <div className={`absolute top-4 right-4 w-9 h-9 rounded-full border-2 flex items-center justify-center font-display font-bold text-sm ${rankStyle(c.rank)}`}>
                  {c.rank}
                </div>

                <div className="flex items-center gap-3 mb-4 pr-10">
                  <div className="w-12 h-12 rounded-2xl bg-sky-gradient text-white font-bold text-lg flex items-center justify-center flex-shrink-0">
                    {c.firstName?.[0]}{c.lastName?.[0]}
                  </div>
                  <div>
                    <h3 className="font-display font-bold text-sky-900">{c.firstName} {c.lastName}</h3>
                    <p className="text-sky-400 text-xs truncate max-w-[200px]">{c.headline}</p>
                  </div>

                  {/* Score ring */}
                  <div className="ml-auto mr-10 flex-shrink-0">
                    <div className="relative w-14 h-14">
                      <svg className="w-14 h-14 -rotate-90" viewBox="0 0 56 56">
                        <circle cx="28" cy="28" r="22" strokeWidth="4" className="stroke-sky-100 fill-none" />
                        <circle cx="28" cy="28" r="22" strokeWidth="4" fill="none"
                          stroke="#0ea5e9" strokeLinecap="round"
                          strokeDasharray={`${(c.matchScore / 100) * 138} 138`} />
                      </svg>
                      <span className="absolute inset-0 flex items-center justify-center font-display font-bold text-sky-700 text-sm">
                        {c.matchScore}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Tags */}
                <div className="flex flex-wrap gap-1.5 mb-3">
                  {(c.strengths || []).slice(0, 2).map((s: string, i: number) => (
                    <span key={i} className="text-xs bg-emerald-50 text-emerald-600 border border-emerald-200 px-2.5 py-1 rounded-full font-semibold">
                      ✓ {s.split('.')[0].substring(0, 30)}
                    </span>
                  ))}
                  {(c.gaps || []).slice(0, 1).map((g: string, i: number) => (
                    <span key={i} className="text-xs bg-amber-50 text-amber-600 border border-amber-200 px-2.5 py-1 rounded-full font-semibold">
                      ⚠ {g.split('.')[0].substring(0, 25)}
                    </span>
                  ))}
                </div>

                {/* AI reasoning excerpt */}
                <div className="bg-sky-50 border-l-4 border-sky-400 rounded-r-xl p-3 mb-4">
                  <p className="text-sky-700 text-xs line-clamp-2">{c.recommendation}</p>
                </div>

                <div className="flex items-center justify-between text-xs text-sky-400">
                  <span>📍 {c.location}</span>
                  <span className="flex items-center gap-1 text-sky-500 font-semibold">
                    View full reasoning <ChevronRight className="w-3 h-3" />
                  </span>
                </div>
              </div>
            ))}
          </div>
        </>
      )}

      {/* Candidate detail modal */}
      {selected && (
        <div className="fixed inset-0 bg-sky-950/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl w-full max-w-2xl max-h-[90vh] overflow-y-auto shadow-sky-lg">
            <div className="sticky top-0 bg-white border-b border-sky-100 px-8 py-5 flex items-center justify-between rounded-t-3xl">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-sky-gradient text-white font-bold text-lg flex items-center justify-center">
                  {selected.firstName?.[0]}{selected.lastName?.[0]}
                </div>
                <div>
                  <h2 className="font-display text-xl font-bold text-sky-900">{selected.firstName} {selected.lastName}</h2>
                  <p className="text-sky-400 text-sm">Rank #{selected.rank} · Score {selected.matchScore}/100</p>
                </div>
              </div>
              <button onClick={() => setSelected(null)} className="text-sky-400 hover:text-sky-700"><X className="w-5 h-5" /></button>
            </div>

            <div className="p-8 space-y-6">
              {/* Score breakdown */}
              <div>
                <h3 className="font-display font-bold text-sky-900 mb-4">Score Breakdown</h3>
                <div className="space-y-3">
                  {Object.entries(selected.scoreBreakdown || {}).map(([k, v]: any) => (
                    <div key={k} className="flex items-center gap-3">
                      <span className="text-sky-600 text-sm capitalize w-40 flex-shrink-0">
                        {k.replace(/([A-Z])/g, ' $1')}
                      </span>
                      <div className="flex-1 h-2 bg-sky-100 rounded-full overflow-hidden">
                        <div className="h-full bg-sky-400 rounded-full" style={{ width: `${v}%` }} />
                      </div>
                      <span className="font-bold text-sky-700 text-sm w-10 text-right">{v}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Strengths & Gaps */}
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-emerald-50 rounded-2xl p-4 border border-emerald-100">
                  <p className="text-emerald-600 text-xs font-bold uppercase tracking-wide mb-3">Strengths</p>
                  <ul className="space-y-2">
                    {(selected.strengths || []).map((s: string, i: number) => (
                      <li key={i} className="text-emerald-800 text-xs flex gap-2">
                        <span className="flex-shrink-0">✓</span> {s}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="bg-amber-50 rounded-2xl p-4 border border-amber-100">
                  <p className="text-amber-600 text-xs font-bold uppercase tracking-wide mb-3">Gaps / Risks</p>
                  <ul className="space-y-2">
                    {(selected.gaps || []).map((g: string, i: number) => (
                      <li key={i} className="text-amber-800 text-xs flex gap-2">
                        <span className="flex-shrink-0">⚠</span> {g}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* AI Recommendation */}
              <div className="bg-sky-50 border-l-4 border-sky-500 rounded-r-2xl p-5">
                <p className="text-sky-500 text-xs font-bold uppercase tracking-wide mb-2">🤖 AI Recommendation</p>
                <p className="text-sky-800 text-sm leading-relaxed">{selected.recommendation}</p>
              </div>

              {/* Skill scores */}
              {selected.skillScores?.length > 0 && (
                <div>
                  <h3 className="font-display font-bold text-sky-900 mb-3">Skill Scores</h3>
                  <div className="space-y-2">
                    {selected.skillScores.map((s: any) => (
                      <div key={s.name} className="flex items-center gap-3">
                        <span className="text-sky-600 text-sm w-32 flex-shrink-0">{s.name}</span>
                        <div className="flex-1 h-2 bg-sky-100 rounded-full overflow-hidden">
                          <div className="h-full rounded-full transition-all"
                            style={{ width: `${s.score}%`, background: s.score >= 70 ? '#10b981' : s.score >= 50 ? '#f59e0b' : '#ef4444' }} />
                        </div>
                        <span className="font-bold text-sky-700 text-sm w-8 text-right">{s.score}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="flex gap-3 pt-2">
                <button className="flex-1 btn-sky">✓ Move to Interview</button>
                <button className="flex-1 bg-red-50 text-red-500 font-semibold px-4 py-2.5 rounded-xl hover:bg-red-100 transition-colors">✗ Reject</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
